### PR TITLE
Make sure its possible to get response code behind http/2 proxy

### PR DESCRIPTION
**Pull request by sven-codeculture**
My traefic proxy returns "HTTP/2 404 "

### CODE REVIEW

**Comment by woutersamaey** [comment]
I just discovered and fixed the same thing, but you beat me to it.
Do prefer my regex as it allows for any number of digits and periods.
```
preg_match('/^HTTP\/([\d\.]+)\s(\d+)/', $lines[$i], $statusLine);
```
In my case I had an Nginx HTTP2 proxy. The line to match is `HTTP/2 404`

**Comment by sven-codeculture** [comment]
Yea, would also be possible. But i don't like your's completely since it would also allow something like ``HTTP/2....2 404``
In the end i do not mind any regexp as long as the issue with the http2 proxy is fixed.

**Comment by NicolasDorier** [comment]
sorry, I did not got notifications of this repo. Waiting @klokit-co to test this PR and merging it.

**Comment by NicolasDorier** [comment]
He told me on mattermost that this fix his issue.

**Pull request merged**
