### PR TITLE
Update to Upstream Version 3.6.2005 of the v2 client repo

### PR DESCRIPTION
**Pull request by mp21-org**
This PR will move the PHP Client for BTCPayServer to the new Upstream Codebase of their v2 repository.

I know this is a massive PR, and we should have a discussion if any of these changes could potentially break other plugins using this client. (in case anyone uses composer with version * or something)

Hope this makes it in.

### CODE REVIEW

**Comment by NicolasDorier** [comment]
I can't really review it. You tried if at least they did not break their own REST API?

**Comment by woutersamaey** [comment]
I will pull it in my Magento 2 plugin and see if it works. If it does, we can at least be certain that basic order creation & payment works.

**Comment by mp21-org** [comment]
Well the basic things (creating an invoice, querrying an invoice) seem to work.

I am using it in 3 projects with the code we had in the [v2](https://github.com/btcpayserver/php-btcpay-client-v2) repo since january

There are also unit tests preconfigured for the btcpay demo mainnet instance which seem to be green (the once supported by btcpayserver):

https://github.com/btcpayserver/php-btcpay-client-v2/blob/master/tests/BtcPaySDK/BtcPayTest.php

Something I noticed this morning: The [Guide.md](https://github.com/btcpayserver/php-btcpay-client-v2/blob/master/GUIDE.md) still contains a ton of bitpay references... that needs some more refinement. :-)

**Comment by woutersamaey** [comment]
I think you also wrote over the README.md. Maybe you can merge the old text with the new, explaining differences?
The previous version was numbered ~~0.2.0~~ 1.0.0 by me. Your version should then be ~~0.3.0~~ 2.0.0 ?

**Comment by woutersamaey** [comment]
> I am using it in 3 projects with the code we had in the v2 repo since january

My Magento module is not on your v2 from jan, but ~~0.2.0~~ 1.0.0 from this repo. My case will be what most people following this repo will experience.

**Comment by mp21-org** [comment]
I went by your tags (the last beeing v1.0.0), but sure we can call it 0.3.0 as well.
I allowed edits by maintainers to my [repo](https://github.com/petzsch/btcpayserver-php-client/), feel free to make edits there to add it to this PR :-)

**Comment by woutersamaey** [comment]
My mistake, I meant 1.0.0. 0.2.0 is old. Corrected previous replies.

**Comment by mp21-org** [comment]
some variable names in the samples still include "bitpay" in their names... don't know if we want to change that as well.

The Readme.md now includes the information from the old readme as well.

Please let me know if there is anything I can do to help with the magento2 plugin.

**Comment by mp21-org** [comment]
any update on this?

**Comment by NicolasDorier** [comment]
hey @woutersamaey @psyb0t  don't hesitate to add @petzsch  as contributor to this repo if you are too busy reviewing the contributions. He has been a member in the community since long ago.

**Comment by woutersamaey** [comment]
@NicolasDorier I've added him to this repo.

Unfortunately not finding the time to check everything.
Personally I'm looking forward to the Greenfield API, making this and the BitPay API compatibility obsolete.

**Comment by mp21-org** [comment]
BitPay updated to v4.0.2007
Will try to get the changes into my repo for this pull request.

**Comment by NicolasDorier** [comment]
@petzsch btw, we don't have to keep compatibility with them now. I did that originally so people could migrate from their API to ours. But now we don't need it.

**Comment by mp21-org** [comment]
Agreed. We should probably shift effort to making a Greenfield API Client available.
Just had a look at the upcoming Invoices endpoint... awesome stuff. 👍 

https://github.com/btcpayserver/btcpayserver/pull/1760

**Comment by mp21-org** [comment]
Closed in favour of Greenfield.

There is no need to break the old bitpay api implementation that people are using, when the way to go will be Greenfield in the foreseeable future.

**Pull request closed without merging**
